### ISSUE TITLE
undefined method `log_class_name=' for RTP::Logger:Class

### ISSUE THREAD

**Issue by ghost** [turboladen/rtsp#25]
Ever since I version bumped to the latest version of rtp and rtsp, I'm getting:

```
undefined method `log_class_name=' for RTP::Logger:Class
/home/deployer/asd/shared/bundle/ruby/2.1.0/gems/rtp-0.1.5/lib/rtp/receiver.rb:5:in `require_relative'
/home/deployer/asd/shared/bundle/ruby/2.1.0/gems/rtp-0.1.5/lib/rtp/receiver.rb:5:in `<top (required)>'
/home/deployer/asd/shared/bundle/ruby/2.1.0/gems/rtsp-0.4.5/lib/rtsp/client.rb:4:in `require'
/home/deployer/asd/shared/bundle/ruby/2.1.0/gems/rtsp-0.4.5/lib/rtsp/client.rb:4:in `<top (required)>'
```

All I have to do to trigger this error is: 

``` ruby
require 'rtsp/client'
```

Any ideas?

**Comment by AndrewBelt** [comment]
Same here. In addition, using the simple example in the README in Ruby 2.2.3 yields the same issue.

    require 'rtsp'
    client = RTSP::Client.new "rtsp://64.202.98.91/sa.sdp"

Looking at the source, I don't see how any of the other files can be loaded at all. Did a recent committer purposely kill this project?

**Comment by turboladen** [comment]
I believe this is related to my updating the log_switch gem to 1.0.0, but rtsp not being greedy enough with its dependency declarations. As you can probably tell from the commit history, I haven't used this gem in quite some time and have been the sole maintainer. PRs are welcome, especially since I no longer have access to any RTSP devices for testing.

**Comment by dblommesteijn** [comment]
Adding `gem 'log_switch', '~> 0.4.0'` to your project's Gemfile will lock versions below `1.0.0`. This is a workaround and needs a proper fix.
