### ISSUE TITLE
`find_all' for nil:NilClass in /lib/rtsp/client.rb:451:in `aggregate_control_track'

### ISSUE THREAD

**Issue by hackeron** [turboladen/rtsp#26]
When I try to run the describe method, I see the following:

```
[5] pry(main)> rtsp = RTSP::Client.new('rtsp://192.168.88.11/')
=> #<RTSP::Client:0x000000028d0070
 @capturer=
  #<RTP::Receiver:0x000000028d7fa0
   @broadcast_type=:unicast,
   @listener=nil,
   @packet_timestamps=[],
   @payload_data=[],
   @rtp_file=#<File:/tmp/rtp_capture.raw20150627-26597-1g0flgj>,
   @rtp_port=9000,
   @sequence_list=[],
   @strip_headers=false,
   @transport_protocol=:UDP>,
 @connection=#<struct Struct::Connection server_url="rtsp://192.168.88.11/", timeout=30, socket=#<TCPSocket:fd 11>, do_capture=true, interleave=false>,
 @cseq=1,
 @play_thread=nil,
 @server_uri=#<URI::Generic:0x000000028d7618 URL:rtsp://192.168.88.11:554/>,
 @session={},
 @session_state=:init>
[6] pry(main)> rtsp.desbribe
NoMethodError: undefined method `desbribe' for #<RTSP::Client:0x000000028d0070>
from (pry):5:in `__pry__'
[7] pry(main)> rtsp.describe
[2015-06-27 17:35:04 +0100] Sending DESCRIBE to rtsp://192.168.88.11:554/
[2015-06-27 17:35:04 +0100] DESCRIBE rtsp://192.168.88.11:554/ RTSP/1.0
[2015-06-27 17:35:04 +0100] CSeq: 1
[2015-06-27 17:35:04 +0100] User-Agent: RubyRTSP/0.4.1 (Ruby 2.0.0-p645)
[2015-06-27 17:35:04 +0100] Accept: application/sdp
[2015-06-27 17:35:04 +0100] 
[2015-06-27 17:35:04 +0100] Received response:
[2015-06-27 17:35:04 +0100] RTSP/1.0 200 OK
[2015-06-27 17:35:04 +0100] CSeq: 1
[2015-06-27 17:35:04 +0100] Server: HuangHe/1.0.0
[2015-06-27 17:35:04 +0100] Date: Sat, 27 Jun 2015 17:47:50 GMT
[2015-06-27 17:35:04 +0100] Content-Type: application/sdp
[2015-06-27 17:35:04 +0100] Content-Base: rtsp://192.168.88.11/
[2015-06-27 17:35:04 +0100] Content-Length: 285
[2015-06-27 17:35:04 +0100] 
[2015-06-27 17:35:04 +0100] v=0
[2015-06-27 17:35:04 +0100] o=StreamingServer 3433055887 1435427270319700 IN IP4 192.168.88.11
[2015-06-27 17:35:04 +0100] s=
[2015-06-27 17:35:04 +0100] e=NONE
[2015-06-27 17:35:04 +0100] c=IN IP4 0.0.0.0
[2015-06-27 17:35:04 +0100] t=0 0
[2015-06-27 17:35:04 +0100] m=video 0 RTP/AVP 96
[2015-06-27 17:35:04 +0100] b=AS:70
[2015-06-27 17:35:04 +0100] a=control:trackID=1
[2015-06-27 17:35:04 +0100] a=rtpmap:96 H264/90000
[2015-06-27 17:35:04 +0100] a=fmtp:96 profile-level-id=42e02a;packetization-mode=1;sprop-parameter-sets=Z0LgKtoBkAlx,aM4wpIA=
NoMethodError: undefined method `find_all' for nil:NilClass
from /var/lib/gems/2.0.0/gems/rtsp-0.4.1/lib/rtsp/client.rb:451:in `aggregate_control_track'
```

**Comment by turboladen** [comment]
I need to update the README, but unfortunately I'm not in a spot any longer to maintain this project. This was a project for my last job and no longer have access to any RTSP devices for testing.
